image:
  repository: greyjoy.icp:8500/samples/app # Specify your cluster CA domain here
  tag: hello-world

ingress:
  enabled: true
  path: /demo/
  rewriteTarget: /

configProperties:
  configMapName: my-config-properties
